#!/usr/bin/env python

import serial
import time


arduinoser = serial.Serial('/dev/ttyACM0', 9600)
go = "Ready!"
done = "Transfer complete!"


string1 = "120,60,135,90,45,150;"
string2 = "160,28,80,75,112,135;"
string3 = "90,120,45,38,27,180;"


print("Establishing Serial Connection....")
time.sleep(2)
print("Connection Established!")

print("Sending motor co-ordinates " + string1 + "\n")
arduinoser.write(string1)
time.sleep(10)
print("Sending motor co-ordinates " + string2 + "\n")
arduinoser.write(string2)
time.sleep(10)
print("Sending motor co-ordinates " + string3 + "\n")
arduinoser.write(string3)



